const actions = {
   STORE_CURRENT_USER: "STORE_CURRENT_USER",
   STORE_QUEUED_TASKS: "STORE_QUEUED_TASKS",
   UPDATE_INDEX_OF_CURRENT_TASK: "UPDATE_INDEX_OF_CURRENT_TASK",
};

export default actions;
